# -*- coding: utf-8 -*-
"""Hospital Management System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hglzvAPKR166BuyeDqt_sRj3PYhhUVSP
"""

class Patient:
    def __init__(self, patient_id, name, age, gender):
        self.patient_id = patient_id
        self.name = name
        self.age = age
        self.gender = gender

class Doctor:
    def __init__(self, doctor_id, name, specialization):
        self.doctor_id = doctor_id
        self.name = name
        self.specialization = specialization

class Appointment:
    def __init__(self, patient_id, doctor_id, date, time):
        self.patient_id = patient_id
        self.doctor_id = doctor_id
        self.date = date
        self.time = time

class Hospital:
    def __init__(self):
        self.patients = []
        self.doctors = []
        self.appointments = []

    def add_patient(self):
      patient_id = input("Enter patient ID: ")
      name = input("Enter patient name: ")
      age = input("Enter patient age: ")
      gender = input("Enter patient gender: ")
      self.patients.append(Patient(patient_id, name, age, gender))
      print("Patient added successfully!")

    def view_patients(self):
        for patient in self.patients:
            print(f"ID: {patient.patient_id}, Name: {patient.name}, Age: {patient.age}, Gender: {patient.gender}")

    def search_patient(self, patient_id):
        for patient in self.patients:
            if patient.patient_id == patient_id:
                print(f"ID: {patient.patient_id}, Name: {patient.name}, Age: {patient.age}, Gender: {patient.gender}")
                return
        print("Patient not found.")

    def add_doctor(self):
        doctor_id = input("Enter doctor ID: ")
        name = input("Enter doctor name: ")
        specialization = input("Enter doctor specialization: ")
        self.doctors.append(Doctor(doctor_id, name, specialization))
        print("Doctor added successfully!")

    def view_doctors(self):
      for doctor in self.doctors:
          print(f"ID: {doctor.doctor_id}, Name: {doctor.name}, Specialization: {doctor.specialization}")

    def search_doctor(self, doctor_id):
        for doctor in self.doctors:
            if doctor.doctor_id == doctor_id:
                print(f"ID: {doctor.doctor_id}, Name: {doctor.name}, Specialization: {doctor.specialization}")
                return
        print("Doctor not found.")

    def book_appointment(self):
        patient_id = input("Enter patient ID: ")
        doctor_id = input("Enter doctor ID: ")
        date = input("Enter appointment date (YYYY-MM-DD): ")
        time = input("Enter appointment time (HH:MM): ")
        self.appointments.append(Appointment(patient_id, doctor_id, date, time))
        print("Appointment booked successfully!")

    def view_appointments(self):
      for appointment in self.appointments:
          print(f"Patient ID: {appointment.patient_id}, Doctor ID: {appointment.doctor_id}, Date: {appointment.date}, Time: {appointment.time}")


if __name__ == "__main__":
    hospital = Hospital()
    while True:
        print("\nHospital Management System")
        print("1. Patient Management")
        print("2. Doctor Management")
        print("3. Appointment Management")
        print("4. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            print("\na. Add Patient\nb. View Patients\nc. Search Patient")
            patient_choice = input("Enter your choice: ")
            if patient_choice == 'a':
              hospital.add_patient()
            elif patient_choice == 'b':
              hospital.view_patients()
            elif patient_choice == 'c':
                patient_id = input("Enter patient ID to search: ")
                hospital.search_patient(patient_id)

        elif choice == '2':
            print("\na. Add Doctor\nb. View Doctors\nc. Search Doctor")
            doctor_choice = input("Enter your choice: ")
            if doctor_choice == 'a':
                hospital.add_doctor()
            elif doctor_choice == 'b':
                hospital.view_doctors()
            elif doctor_choice == 'c':
                doctor_id = input("Enter doctor ID to search: ")
                hospital.search_doctor(doctor_id)
        elif choice == '3':
            print("\na. Book Appointment\nb. View Appointments")
            appointment_choice = input("Enter your choice: ")
            if appointment_choice == 'a':
                hospital.book_appointment()
            elif appointment_choice == 'b':
                hospital.view_appointments()
        elif choice == '4':
            print("Exiting...")
            break
        else:
            print("Invalid choice. Please try again.")